name: "Summarize Checkov Scan"
description: "Summarizes Checkov SARIF scan results and appends them to GitHub Step Summary"
inputs: {}

branding:
  icon: 'package'
  color: 'blue'
  logo: 'https://raw.githubusercontent.com/subhamay-bhattacharyya-gha/cfn-parameters-action/main/logo.png'

runs:
  using: "node24"
  main: "main.js"